### PR TITLE
Add support for GHC 8.4 and 8.6

### PR DESCRIPTION
**Pull request by edsko**

### CODE REVIEW

**Comment by edsko** [comment]
At some point we might want to be smarter about how we deal with these ghc versions but for now I just followed the structure that was already there.

**Comment by lierdakil** [comment]
Thanks. Will also tweak the start-of-message regex for new Cabal output (see below) and push out a release.

On Cabal's new output format, basically, cabal-install now also shows the source line containing the error. It wouldn't be a problem, but that line has zero indentation, which our parser treats as a start of a new message, which leads to unsightliness. 
```
src/GhcModMain.hs:28:13: error:
    • Couldn't match type ‘Char’ with ‘[Char]’
      Expected type: [String]
        Actual type: [Char]
    • In the expression: "asd"
      In an equation for ‘afunction’: afunction = "asd"
   |
28 | afunction = "asd"
   |             ^^^^^
```

**Comment by lierdakil** [comment]
Also, side note: don't bump version in package.json in the future. Also, I generate changelog from commit messages on release, so you don't really need to touch that either.

**Comment by edsko** [comment]
> Also, side note: don't bump version in package.json in the future. Also, I generate changelog from commit messages on release, so you don't really need to touch that either.

Gotcha, was just trying to be thorough :)

**Pull request merged**
