### PR TITLE
Use fully qualified component name

### PR DESCRIPTION
**Pull request by edsko**
In a directory structure with multiple packages, each with a component
with the same name, we must use the fully qualified name. For example,
instead of just using `test:test` (the test suite named `test`) we
should use `foo:test:test` (the test suite named `test` in package
`foo`).

### CODE REVIEW

**Comment by lierdakil** [comment]
Hi. Sorry it took a while to get to this, pretty busy with teaching this semester.

So, first of all, thanks for creating the PR. I have a few questions though.

1. Are we sure this will work for all builders? I.e. for legacy cabal-v1, cabal-v2 and stack? If not, probably better handle this in builder code (by overriding `CabalBase::component()` perhaps)

2. Doesn't the `all` target need similar treatment?
https://github.com/atom-haskell/ide-haskell-cabal/blob/469221a69fb38706ca8fe56727e28074eab2fdbc/src/ide-backend.ts#L350-L356

    Also, apparently there's a copy-paste error here, `newTarget = newTarget = ...`. It doesn't affect observable behaviour, but might as well fix it while we're at it, otherwise I might forget and it will haunt the code for years to come...

3. If the answer to (2) is 'yes', then do you suppose handling this in `CabalBase::component()` would be a better fit? After all, `target` does already contain all the information needed, between `component` and `project`.
https://github.com/atom-haskell/ide-haskell-cabal/blob/469221a69fb38706ca8fe56727e28074eab2fdbc/src/builders/base/cabal.ts#L40-L49

**Comment by edsko** [comment]
Yes, I guess you are right, we should do this for `v2-build` specifically, though `v1` and `stack` will probably require similar changes. Doing this in `component` makes sense. Do you want me to update the PR?

**Comment by edsko** [comment]
For `stack` the same syntax is valid. For `v1-build` perhaps not, but it's not so relevant there, since that anyway doesn't support a `cabal.project` file (or similar) and so the situation is less likely to arise.

**Comment by lierdakil** [comment]
If you could update the PR, that would be great. Thanks in advance.

**Comment by edsko** [comment]
Wait, I don't think I fully understand after all, for two reasons. If we want to modify `component()` instead (probably in `cabal-v2`), the case for `component` ought to be simple:

```typescript
      case 'component':
        return [this.opts.target.name + ":" + this.opts.target.component]
```

However, that does not work, since at this stage we don't have that info anymore, all we have is a `string`? (Mind, I have never written TypeScript before :) )

```typescript
export type TargetParamTypeForBuilder = (
  | {
      type: 'component'
      component: string
    }
  | {
      type: 'all'
      targets: Util.ITarget[]
    }
  | {
      type: 'auto'
    }) &
  ProjectDesc
```

Also, for the `all` case, I'm not sure that there is anything to do after all. `all` doesn't specify a component name at all, so there is no need to disambiguate?

**Comment by lierdakil** [comment]
```ts
export type TargetParamTypeForBuilder = (
  | {
      type: 'component'
      component: string
    }
  | {
      type: 'all'
      targets: Util.ITarget[]
    }
  | {
      type: 'auto'
    }) &
  ProjectDesc
```
Notice `& ProjectDesc`. This means that any instance of `TargetParamTypeForBuilder` is also an instance of `ProjectDesc`, i.e. contains properties `project:string` and `dir:string|undefined`. Where `project` is specified as the `name` from Cabalfile (notice line 351 here for instance:
https://github.com/atom-haskell/ide-haskell-cabal/blob/469221a69fb38706ca8fe56727e28074eab2fdbc/src/ide-backend.ts#L350-L356
)

That is to say, `[this.opts.target.project + ":" + this.opts.target.component]` will work.

So defining something like this in `cabal-v2.ts` would do it I think:
```ts
  protected component(): string[] {
    if (this.opts.target.type === 'component') {
      return [`${this.opts.target.project}:${this.opts.target.component}`]
    } else {
      return super.component()
    }
  }
```

Now then, `all` grabs all build targets/components from Cabalfile, then passes a list of those to the builder command. IIRC, you'll want to do something like
```ts
this.opts.target.targets.map((x) => `${this.opts.target.project}:${x.target}`)
```

There are some unfortunate property name choices here wrt `target` vs `component`, so this might look a bit more confusing than it has any right to be. Sorry, some of it was coded using caffeine as fuel.

Side note, it would seem you're not utilizing the full power TypeScript offers here. If you're hacking on this using Atom, consider installing, f.ex. atom-typescript package (disclaimer: this is a bit of self-advertisement) and checking what autocompletion suggests for `this.opts.target.` for instance. For me at least, this helps reduce required mental effort somewhat.

**Comment by lierdakil** [comment]
Also, while at it, since two out of three builders support this syntax, perhaps better redefine this in `CabalBase` and override in `cabal-v1.ts` to avoid code duplication? Honestly, I'm not entirely sure how `stack` handles multi-cabalfile projects.

**Comment by edsko** [comment]
Ok, force-pushed. I ended up not modifying the one for stack, since I don't use stack and I don't feel entirely comfortable changing something without understanding it very well. I take your point re duplication, but actually I think even if stack is the same syntax, I think this is the _right_ kind of duplication: after all, those tools are independent from each other and tying them together by assuming the same syntax in a base class feels somewhat wrong to me.

**Comment by lierdakil** [comment]
Hmm. Apparently tests are broken. I'll have to figure those out, probably soon-ish. Anyway, thanks. I'll merge now and try to push out a release later today.

**Comment by edsko** [comment]
Thanks! And yes, the test failure didn't seem related to my change so I didn't investigate further.

**Comment by edsko** [comment]
Thanks for the release :)

**Pull request merged**
